export const FETCH_LOCAL_AUTHORITIES = 'FETCH_LOCAL_AUTHORITIES';
export const FETCH_ESTABLISHMENTS_PROFILE = 'FETCH_ESTABLISHMENTS_PROFILE';

export const SELECT_LOCAL_AUTHORITY = 'SELECT_LOCAL_AUTHORITY';

export const FETCH_LOCAL_AUTHORITIES_PENDING = 'FETCH_LOCAL_AUTHORITIES_PENDING';
export const FETCH_LOCAL_AUTHORITIES_FULFILLED = 'FETCH_LOCAL_AUTHORITIES_FULFILLED';
export const FETCH_LOCAL_AUTHORITIES_REJECTED = 'FETCH_LOCAL_AUTHORITIES_REJECTED';

export const FETCH_ESTABLISHMENTS_PROFILE_PENDING = 'FETCH_ESTABLISHMENTS_PROFILE_PENDING';
export const FETCH_ESTABLISHMENTS_PROFILE_FULFILLED = 'FETCH_ESTABLISHMENTS_PROFILE_FULFILLED';
export const FETCH_ESTABLISHMENTS_PROFILE_REJECTED = 'FETCH_ESTABLISHMENTS_PROFILE_REJECTED';

export const SHOW_NOTIFICATION_BAR = 'SHOW_NOTIFICATION_BAR';
export const HIDE_NOTIFICATION_BAR = 'HIDE_NOTIFICATION_BAR';
